default: &default
  adapter: postgresql
  timeout: 5000

development:
  <<: *default
  database: newscout_development

test:
  <<: *default
  database: newscout_test

production:
  <<: *default
  database: newscout_production
